### ISSUE TITLE
Automate automatic publishing of images to Docker Hub

### ISSUE THREAD

**Issue by gabmontes** [bloq/memproxyjs#15]
Enable automated builds and automate tests to publish new images on version tags applied to `master`.

See: https://docs.docker.com/docker-hub/builds/

**Comment by jgarzik** [comment]
In theory Docker Hub auto-build is already enabled, as it was for `memproxy`.

For unknown reasons that need to be investigated, pushing to `memproxy` successfully triggers DH autobuild, but pushing to this repo, `memproxyjs`, does not.

**Comment by gabmontes** [comment]
@jgarzik it looks like there given there are no build rules set for this repo, no images are being built.

Assign this issue to me if you want and I will work on it.

**Comment by gabmontes** [comment]
Done.
