### ISSUE TITLE
Configure repository branch protection

### ISSUE THREAD

**Issue by gabmontes** [bloq/memproxyjs#3]
The `master` branch should be protected. Minimum suggested configuration:

- [x] Require pull request reviews before merging
  - Required approving reviews: 1
  - [x] Dismiss stale pull request approvals when new commits are pushed
  - [ ] Require review from Code Owners
  - [ ] Restrict who can dismiss pull request reviews
- [ ] Require status checks to pass before merging
- [x] Require signed commits
- [ ] Require linear history
- [x] Include administrators
- [ ] Restrict who can push to this branch

Additional settings like more required approvals, [code owners](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) settings, should be configured too.

**Comment by gabmontes** [comment]
@daniel-bloq @jgarzik can you please grant me admin permissions on this repo to configure its settings?

**Comment by jgarzik** [comment]
@gabmontes done.   Usual permission is dev=Write, devops=Admin.  Added you as exception.

**Comment by gabmontes** [comment]
Done.
